project_name: air-quality-lapaz
description: "Air Quality Data Analysis in La Paz, Bolivia"
author: Andres Chirinos
created_date: 2025-06-17
version: 1.0.0

data_dir: "data"
output_dir: "output"

github_actions:
  artifact:
    logs:
      retention_days: 14
    data:
      retention_days: 14

drive:
  folder_id: "1Ib6A-TqdurUPOLKsvs1mYuH4PMSLN4uk"

kaggle:
  dataset_id: "andreschirinos/air-quality-lapaz"
  is_public: true

